[project]
name = "llm-mcp-client"
version = "0.1a0"
description = "Access tools from MCP servers as LLM tools"
readme = "README.md"
authors = [{name = "Simon Willison"}]
license = "Apache-2.0"
classifiers = []
requires-python = ">=3.10"
dependencies = [
    "llm",
    "mcp>=2.0.0"
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.uv]
package = true

[project.urls]
Homepage = "https://github.com/simonw/llm-mcp-client"
Changelog = "https://github.com/simonw/llm-mcp-client/releases"
Issues = "https://github.com/simonw/llm-mcp-client/issues"
CI = "https://github.com/simonw/llm-mcp-client/actions"

[project.entry-points.llm]
mcp_client = "llm_mcp_client"

[dependency-groups]
dev = ["pytest", "pytest-asyncio"]
